"""Starter skill vocabulary: canonical name -> (category, aliases). Extended at seed time from data/knowledge."""

SEED: dict[str, tuple[str, list[str]]] = {
    "JavaScript": ("language", ["js", "javascript", "ecmascript", "es6"]),
    "TypeScript": ("language", ["ts", "typescript"]),
    "Python": ("language", ["python", "python3", "py"]),
    "Java": ("language", ["java"]),
    "C++": ("language", ["c++", "cpp"]),
    "C#": ("language", ["c#", "csharp"]),
    "Go": ("language", ["go", "golang"]),
    "Rust": ("language", ["rust"]),
    "SQL": ("language", ["sql"]),
    "React": ("framework", ["react", "reactjs", "react.js"]),
    "Next.js": ("framework", ["next", "nextjs", "next.js"]),
    "Vue": ("framework", ["vue", "vuejs", "vue.js"]),
    "Node.js": ("framework", ["node", "nodejs", "node.js"]),
    "FastAPI": ("framework", ["fastapi"]),
    "Flask": ("framework", ["flask"]),
    "Django": ("framework", ["django"]),
    "PostgreSQL": ("database", ["postgres", "postgresql", "psql"]),
    "MySQL": ("database", ["mysql"]),
    "MongoDB": ("database", ["mongo", "mongodb"]),
    "Redis": ("database", ["redis"]),
    "Docker": ("devops", ["docker", "containers"]),
    "Kubernetes": ("devops", ["k8s", "kubernetes"]),
    "AWS": ("cloud", ["aws", "amazon web services"]),
    "Azure": ("cloud", ["azure"]),
    "GCP": ("cloud", ["gcp", "google cloud"]),
    "Git": ("tool", ["git", "github", "gitlab"]),
    "CI/CD": ("devops", ["ci/cd", "cicd", "github actions", "jenkins"]),
    "Machine Learning": ("ai", ["ml", "machine learning"]),
    "Deep Learning": ("ai", ["deep learning", "dl"]),
    "NLP": ("ai", ["nlp", "natural language processing"]),
    "PyTorch": ("ai", ["pytorch", "torch"]),
    "TensorFlow": ("ai", ["tensorflow", "tf"]),
    "Scikit-Learn": ("ai", ["scikit-learn", "sklearn"]),
    "LangChain": ("ai", ["langchain"]),
    "LangGraph": ("ai", ["langgraph"]),
    "RAG": ("ai", ["rag", "retrieval augmented generation", "retrieval-augmented generation"]),
    "Neo4j": ("database", ["neo4j"]),
    "ChromaDB": ("database", ["chroma", "chromadb"]),
    "Excel": ("tool", ["excel", "microsoft excel", "ms excel"]),
    "QuickBooks": ("tool", ["quickbooks"]),
    "Financial Reporting": ("accounting", ["financial reporting", "financial statements"]),
    "Auditing": ("accounting", ["audit", "auditing"]),
    "AutoCAD": ("engineering", ["autocad"]),
    "MATLAB": ("engineering", ["matlab"]),
    "PLC": ("engineering", ["plc", "plc programming"]),
    "Patient Care": ("medicine", ["patient care"]),
    "Communication": ("soft", ["communication", "communications"]),
    "Leadership": ("soft", ["leadership", "team leadership"]),
    "Project Management": ("soft", ["project management", "pmp"]),
}
